disabled = false
languageCode = "zh-cn"
languageName = "中文"
weight = 1
title = "Daydream Nation"

[params]
  displayName = "zh-cn"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Cigar"
   email = "2013189697zsj@gmail.com"
   image = "img/author.jpg"
   imageQuality = 96
   headline = "Noise & Feedback / 赛博浪人"
   bio = "在废墟中构建白日梦国度。喜欢大卫·林奇、Sonic Youth 和 Vim"
   links = [
     { email = "mailto:2013189697zsj@gmail.com" },
     { github = "https://github.com/username" },
   ]
