baseURL = 'https://example.org/' # 部署时会自动替换，先不用管
languageCode = 'zh-cn'
title = 'CineSigil0 的技术博客'
theme = 'PaperMod'

[params]
  defaultTheme = "auto" # 跟随系统深色模式
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true # 代码块复制按钮

  [params.profileMode]
    enabled = true
    title = "CineSigil0"
    subtitle = "WezTerm / Nvim / Zsh"
    # 可以在这里加你的 GitHub 链接，以后再配
    
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 20
